---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hf-token
  namespace: default
spec:
  encryptedData:
    HF_TOKEN: AgADnfoan4cSu65yhDlSwtZAPtJoYbbd6NSUpR55fe/iLM4tq6wHq7aKHknYL7RC3E/6Gp4tLKYG3pAMdAE8x/aDt+ZghMRpczMKskLAO99VaFwtmeFuXzcae0wer426/cPfrqtza/M6HYGCypkdkx3nSmyVJcR6Ju4N2UBV5dkQJa4d5vJUCjDRmwd3Co4iJkwrpE1E2Qu49ktytq3FEIFoGEndOViBngSSpV0M3dvn1to2mCSt8NdLMilkQG9WZQ/hXNCjRhDqElE6MUHA/Ncm5n6cvbNvsp/FS5Jmvu7d/vmamF6KNgw0Fapi1bBFz9UBgLs+Z8wCzdBTPGpBvGdELDZ9K9uZSJYHQxQUunRyk0aXD5nfwd4RrEcK8Bo/E1fNIkyEzh1JGKqK3Gb83cgUkX/ZK7er/dy5sym1/PLhBcmmDcEBPaBiZZMSBmOs2VeUc3BOF1/a3qu3btYefLIYdxfeCkVUEo4lvBoaH4113O/pdHYKyEFjcOpEqEzO8ZqdnNQ2TUEsnr2M31jTQ1IkR1bZqTU92ojFFTS8D1nvGRgM/9HgjZDjlqSpG5O2TincLttVbmKYsgws78viuUoAePlZ2EoQn2sGaTHxZRdBl5GF5N7Z6gKb6rFd/OFQm0YZEVMhY+S3sH3mire5ipQ5xHbkQrm9TuT7JyVmkkkwAeqIHaDdZXSB5uFw0gzVtB3pYeIq8ORmgX11d5GPDlCjU+NCbMS/sM3VBYd02n4jncl8oHvh
  template:
    metadata:
      name: hf-token
      namespace: default
