---
apiVersion: batch/v1
kind: Job
metadata:
  name: model-download
spec:
  backoffLimit: 3
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        app: model-download
    spec:
      restartPolicy: Never
      containers:
        - name: model-download
          image: python:3.10-slim
          command: ["sh", "-c"]
          envFrom:
            - secretRef:
                name: hf-token
          env:
            - name: MODEL_NAME
              value: "Qwen/Qwen3-8B"
            - name: HF_HOME
              value: /model-store
            - name: HF_XET_HIGH_PERFORMANCE
              value: "1"
            - name: MODEL_REVISION
              value: b968826d9c46dd6066d109eabc6255188de91218
          args:
            - |
              set -eux
              pip install --no-cache-dir -U huggingface_hub 
              hf download $MODEL_NAME --revision $MODEL_REVISION
          volumeMounts:
            - name: model-cache
              mountPath: /model-store
      volumes:
      - name: model-cache
        persistentVolumeClaim:
          claimName: model-cache