apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kgateway
  namespace: flux-system
spec:
  ref:
    # tag: "v2.1.2"
    digest: "sha256:77e1b7a96edd4032cda31bbb7aaf70a91fead331c63e98e341cbf38c53ffd683"
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy