apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kgateway
  namespace: flux-system
spec:
  ref:
    # tag: "v2.1.2"
    # digest: "sha256:86e6dc75ea16862125344fb75df8a45096a524d797eeb984e54dcbbc61c4905a"
    digest: "sha256:4249a3aed5172465281e3a5aa1d1b8d68bffd4353353a804c79990b163adac21"
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy