---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kgateway-crds
  namespace: flux-system
spec:
  interval: 10m
  url: oci://cr.kgateway.dev/kgateway-dev/charts/kgateway-crds
