---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kgateway
  namespace: flux-system
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: kgateway
    namespace: flux-system
  install:
    crds: Skip
    strategy:
      name: RemediateOnFailure
      retryInterval: 5m 
    remediation:
      retries: 3
      remediateLastFailure: true
  upgrade:
    crds: Skip
    strategy:
      name: RemediateOnFailure
      retryInterval: 5m 
    remediation:
      retries: 3
      remediateLastFailure: true
  driftDetection:
    mode: warn
  targetNamespace: kgateway-system